name: Marbit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  device_info: ^2.0.3
  flutter:
    sdk: flutter
  fl_chart: ^0.40.6
  flutter_funding_choices: ^0.3.0+2
  flutter_inner_drawer: 
    git: 
      url: https://github.com/kenjishiromajp/flutter_inner_drawer 
      ref: kenjishiromajp-update-for-2.12-null-safety-casting
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.1.5
  flutter_native_timezone: ^2.0.0
  flutter_neumorphic: ^3.2.0
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  implicitly_animated_reorderable_list: ^0.4.2
  in_app_review: ^2.0.3
  intl: ^0.17.0
  native_admob_flutter: ^1.5.0
  rich_text_controller: ^1.4.0
  rive_splash_screen: ^0.1.0
  scroll_to_index: ^2.1.1
  shared_preferences: ^2.0.11
  timezone: ^0.8.0
  tutorial_coach_mark: ^1.2.1
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  week_of_year: ^2.0.0
  workmanager: ^0.4.1
  collection: ^1.15.0-nullsafety.4
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - test.riv
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-ExtraBold.ttf
        - asset: fonts/Lexend-Bold.ttf
        - asset: fonts/Lexend-SemiBold.ttf
        - asset: fonts/Lexend-Medium.ttf
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-Light.ttf
        - asset: fonts/Lexend-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
